config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15 }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel",
                                    mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render partial: 'message', locals: { message: message }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new

  end

  def create
    user = User.find_by(username: params[:user][:username])

    if user && user.authenticate(params[:user][:password])
      # happy path
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"

      redirect_to root_path
    else
      flash[:error] = "There was something wrong with your login information"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"

    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.slim
h4.ui.center.aligned.medium.icon.header
  i.circular.orange.coffee.icon
  | Say Something

.ui.two.column.grid
  .twelve.wide.column
    .ui.fluid.raised.card.chatbox
      .content id="messages"
        .ui.feed id="message-container"
          = render @messages

      .extra.content
        = form_for(@message, html: { class: "ui reply form", role: "form" }, url: message_path, remote: true) do |f|
          .field
            .ui.fluid.icon.input
              = f.text_field :body
              = f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe

  .four.wide.column
    .ui.fluid.raised.card.chatbox
      .content
        .ui.inverted.vertical.menu
          a.active.item
            | Home
          a.item
            | Messages
          a.item
            | Friends

app/views/layouts/_messages.html.slim
- flash.each do |message_type, message_content|
  .ui.message.transition class = "#{message_type}"
    i.close.icon
    .header
      | #{message_content}

app/views/layouts/_navigation.html.slim
= link_to "Chatroom", root_path, class: "item"
a.item Messages
.right.menu
  .ui.dropdown.item
    | Account
    i.dropdown.icon
    .menu
      - if logged_in?
        = link_to "Log Out", logout_path, method: :delete, class: "item"
      - else
        = link_to "Log In", login_path, class: "item"
  - if !logged_in?
    .item
      = link_to "Log In", login_path, class: "ui primary button"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.slim
.event
  .content
    .summary
      em #{message&.user&.username}
      | : #{message.body}